- name: Deploy climate4R jupyterhub
  hosts: all
  vars:
    user: "{{ ansible_user }}"
    jupyterhub_domain: hub.ipcc.ifca.es
    jupyterhub_users: "{{ ansible_env.HOME }}/climate4r-users"
    jupyterhub_data: "{{ ansible_env.HOME }}/climate4r-data"
  vars_files:
    - authenticator-{{ inventory_hostname }}.yml
  roles:
    - jupyterhub
  pre_tasks:
    - name: Create mountpoints
      file: state=directory path={{ ansible_env.HOME }}/{{ item }}
      with_items: [climate4r-users, climate4r-data]

    - name: Add climate4r-users to /etc/fstab
      become: True
      lineinfile:
        path: /etc/fstab
        line: "{{ fstab_users }}"
      when: fstab_users is defined

    - name: Add climate4r-data to /etc/fstab
      become: True
      lineinfile:
        path: /etc/fstab
        line: "{{ fstab_data }}"
      when: fstab_data is defined

    - name: Add hostname to /etc/hosts
      become: True
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 {{ ansible_hostname }}
  tasks:
    - name: Add conda to user bashrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: >-
          . {{ miniconda_prefix }}/etc/profile.d/conda.sh

    - name: Copy user whitelist
      copy: src=whitelist dest={{ jupyterhub_runtime }}
